Repository TronWatch/TronLink, pull requests merged in 2018-07, with the labels that each got.

#86 symlink commands for windows and unix systems
  package.json
Labels: review

#88 Fixes #83 - Test travis integration
  .travis.yml
  package.json
Labels: enhancement, review

#87 Fixes #61 - Updates the package and manifest details
  .travis.yml
  manifest.json
  package.json
Labels: enhancement, review

#90 Update readme
  README.md
Labels: enhancement, review

#92 Fixes #44 - Introduces JSDOC documentation
  app/pageHook/api/v1/index.js
  app/pageHook/index.js
  package.json
Labels: Documentation, Website API, enhancement, review

#93 New coloured icon
  static/icon128.png
Labels: enhancement, review

#94 Fixes #91 - Remove need for spaces in computed properties
  .eslintrc.js
  app/backgroundScript/wallet.js
  app/lib/utils.js
  app/pageHook/api/v1/index.js
Labels: enhancement, review

#96 Fixes #95 - Adds address validation to the Web API and backgroundScript
  app/backgroundScript/index.js
  app/lib/constants.js
  app/lib/utils.js
  app/pageHook/api/v1/index.js
Labels: Website API, enhancement, review

#98 Fixes #97 - Changes the structure of the popup
  app/popup/.env
  app/popup/src/App.js
  app/popup/src/Icons.js
  app/popup/src/components/App/App.css
  app/popup/src/components/App/index.js
  app/popup/src/components/App/reset.css
  app/popup/src/components/Header/AccountView/AccountView.css
  app/popup/src/components/Header/AccountView/index.js
  app/popup/src/components/Header/Header.css
  app/popup/src/components/Header/Send/Send.css
  app/popup/src/components/Header/Send/index.js
  app/popup/src/components/Header/index.js
  app/popup/src/components/Icons.js
  app/popup/src/components/Main/Content/AccountView/Transactions/Transaction.js
  app/popup/src/components/Main/Content/Content.css
  app/popup/src/components/Main/Content/index.js
  app/popup/src/components/Main/Header/index.js
  app/popup/src/components/Main/Main.css
  app/popup/src/components/Main/Send.js
  app/popup/src/components/Main/index.js
  app/popup/src/index.css
  app/popup/src/index.js
  app/popup/src/pages/Account/AccountView/AccountView.css
  app/popup/src/pages/Account/AccountView/Tokens/Tokens.css
  app/popup/src/pages/Account/AccountView/Tokens/index.js
  app/popup/src/pages/Account/AccountView/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Account/AccountView/Transactions/Transaction/index.js
  app/popup/src/pages/Account/AccountView/Transactions/Transactions.css
  app/popup/src/pages/Account/AccountView/Transactions/index.js
  app/popup/src/pages/Account/AccountView/index.js
  app/popup/src/pages/Account/index.js
  app/popup/src/pages/Give/GiveView/Give.css
  app/popup/src/pages/Give/GiveView/index.js
  app/popup/src/pages/Give/index.js
  app/popup/src/pages/Import/Import.css
  app/popup/src/pages/Import/index.js
  app/popup/src/pages/Queue/CreateSmartcontract/CreateSmartContract.css
  app/popup/src/pages/Queue/CreateSmartcontract/index.js
  app/popup/src/pages/Queue/Queue.css
  app/popup/src/pages/Queue/SendTRX/SendTRX.css
  app/popup/src/pages/Queue/SendTRX/index.js
  app/popup/src/pages/Queue/index.js
  app/popup/src/pages/Send/SendView/Send.css
  app/popup/src/pages/Send/SendView/index.js
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Settings/SettingsView/Settings.css
  app/popup/src/pages/Settings/SettingsView/index.js
  app/popup/src/pages/Settings/index.js
  app/popup/src/pages/Welcome/Welcome.css
  app/popup/src/pages/Welcome/index.js
  app/popup/src/reducers/wallet.js
Labels: enhancement, review
