Repository TronWatch/TronLink, pull requests merged in 2018-09, with the labels that each got.

#154 Correct smart contract rpc call output
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/backgroundScript/websocket.js
  app/lib/utils.js
  app/popup/src/components/Icons.js
  app/popup/src/pages/Import/MnemonicPhrase/index.js
  app/popup/src/pages/Import/PrivateKey/index.js
  app/popup/src/pages/Import/TronScan/index.js
  app/popup/src/pages/Import/TronWatch/index.js
  app/popup/src/pages/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Transactions/Transaction/index.js
  app/popup/src/translations/en.json
  package-lock.json
Labels: User Interface, bug, review

#158 CSS Cleanup
  app/popup/src/components/App/Animations.css
  app/popup/src/components/App/App.css
  app/popup/src/components/Button/Button.css
  app/popup/src/pages/Accounts/Accounts.css
  app/popup/src/pages/Settings/Settings.css
Labels: review

#159 Restructure packages
  .eslintignore
  app/popup/package-lock.json
  app/popup/package.json
  app/popup/yarn.lock
  install.js
  package.json
  yarn.lock
Labels: enhancement, review

#161 Freeze unfreeze
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/constants.js
  app/pageHook/api.js
  app/popup/src/components/Queue/Renderers/Freeze.js
  app/popup/src/components/Queue/Renderers/Unfreeze.js
  app/popup/src/components/Queue/index.js
  app/popup/src/translations/en.json
  yarn.lock
Labels: review

#163 Fix freeze and unfreeze rpc output
  app/backgroundScript/index.js
Labels: bug, review

#166 Switch client API to TronWeb
  app/backgroundScript/index.js
  app/backgroundScript/nodeSelector.js
  app/backgroundScript/wallet.js
  app/backgroundScript/websocket.js
  app/contentScript/index.js
  app/lib/AccountHandler.js
  app/lib/communication/PortChild.js
  app/lib/communication/PortHost.js
  app/lib/constants.js
  app/lib/mapTransaction/contracts.json
  app/lib/mapTransaction/index.js
  app/lib/messages/LinkedRequest.js
  app/lib/messages/LinkedResponse.js
  app/lib/utils.js
  app/pageHook/api.js
  app/pageHook/index.js
  app/popup/src/components/Queue/Queue.css
  app/popup/src/components/Queue/Renderers/CreateSmartContract.js
  app/popup/src/components/Queue/Renderers/Freeze.js
  app/popup/src/components/Queue/Renderers/IssueAsset.js
  app/popup/src/components/Queue/Renderers/SendAsset.js
  app/popup/src/components/Queue/Renderers/SendTron.js
  app/popup/src/components/Queue/Renderers/SignedTransaction.js
  app/popup/src/components/Queue/Renderers/TransferContract.js
  app/popup/src/components/Queue/Renderers/TriggerSmartContract.js
  app/popup/src/components/Queue/Renderers/Unfreeze.js
  app/popup/src/components/Queue/index.js
  app/popup/src/pages/Send/AddressView/AddressView.css
  app/popup/src/pages/Settings/index.js
  app/popup/src/pages/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Transactions/Transaction/index.js
  app/popup/src/translations/en.json
  package.json
  yarn.lock
Labels: Node, Popup API, Smart Contracts, User Interface, Website API, enhancement, review

#167 Handle smart contract signing
  app/backgroundScript/index.js
  app/contentScript/index.js
  app/lib/mapTransaction/index.js
  app/pageHook/ExtensionProvider.js
  app/pageHook/index.js
  yarn.lock
Labels: Website API, bug, review

#168 "Force" popup to open in top left of the browser
  app/backgroundScript/index.js
Labels: User Interface, enhancement, review

#170 1.0.2: Renderer for TriggerSmartContract
  app/backgroundScript/index.js
  app/popup/src/components/Queue/Queue.css
  app/popup/src/components/Queue/Renderers/SignedTransaction.js
  app/popup/src/components/Queue/Renderers/TriggerSmartContract.js
  app/popup/src/translations/en.json
  manifest.json
  package.json
Labels: Smart Contracts, User Interface, enhancement, review

#172 reenable sending trx using popup with tronweb
  app/backgroundScript/index.js
  app/popup/src/components/Queue/Renderers/TransferContract.js
  manifest.json
  package.json
Labels: review

#173 reverse transaction order
  app/lib/utils.js
  manifest.json
  package.json
Labels: review

#176 Change TronWeb to our internal fork
  app/lib/AccountHandler.js
  manifest.json
  package.json
  yarn.lock
Labels: bug, enhancement, review
