Repository TronWatch/TronLink, pull requests merged in 2018-10, with the labels that each got.

#178 1.0.9 beta
  app/lib/communication/popup/PopupHost.js
  app/popup/src/components/Welcome/Welcome.css
  app/popup/src/components/Welcome/index.js
  app/popup/src/index.js
  app/popup/src/pages/Send/Send.css
  app/popup/src/pages/Send/index.js
  app/popup/src/reducers/wallet.js
  manifest.json
  package.json
  yarn.lock
Labels: User Interface, enhancement, review

#181 1.0.10-beta: Add token sending, change default nodes
  app/backgroundScript/index.js
  app/backgroundScript/nodeSelector.js
  app/backgroundScript/wallet.js
  app/lib/AccountHandler.js
  app/lib/communication/popup/PopupClient.js
  app/lib/communication/popup/PopupHost.js
  app/lib/utils.js
  app/popup/src/components/Welcome/Welcome.css
  app/popup/src/pages/Send/AddressView/index.js
  app/popup/src/pages/Send/Send.css
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Settings/index.js
  app/popup/src/pages/Transactions/AccountHeader/index.js
  app/popup/src/pages/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Transactions/Transaction/index.js
  app/popup/src/translations/en.json
  manifest.json
  package.json
  yarn.lock
Labels: User Interface, bug, enhancement, review

#183 1.0.11 beta: Add in some contract renderers, filter out missing transactions
  app/backgroundScript/wallet.js
  app/popup/src/components/Queue/Renderers/AssetIssueContract.js
  app/popup/src/components/Queue/Renderers/ParticipateAssetIssueContract.js
  app/popup/src/components/Queue/Renderers/SignedTransaction.js
  app/popup/src/components/Queue/Renderers/TransferAssetContract.js
  app/popup/src/index.js
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Transactions/Transaction/index.js
  app/popup/src/pages/Transactions/Transactions.css
  app/popup/src/pages/Transactions/index.js
  app/popup/src/translations/en.json
  app/popup/src/translations/fr.json
  app/popup/src/translations/pt.json
  manifest.json
  package.json
Labels: User Interface, enhancement, review

#184 RC 1.1.1
  .gitignore
  app/backgroundScript/nodeSelector.js
  manifest.json
  package.json
Labels: review

#185 v1.1.1
  manifest.json
  package.json
Labels: review

#186 Update README.md
  README.md
Labels: review

#187 Fix webstore link
  README.md
Labels: review

#188 1.1.2: Remove faucet, fix token dropdown overflow
  app/popup/src/components/App/index.js
  app/popup/src/pages/Redeem/Redeem.css
  app/popup/src/pages/Redeem/index.js
  app/popup/src/pages/Send/Send.css
  app/popup/src/pages/Transactions/index.js
  app/popup/src/translations/en.json
  manifest.json
  package.json
Labels: bug, enhancement, review

#189 1.1.3
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/contentScript/index.js
  app/pageHook/index.js
  manifest.json
  package.json
Labels: bug, review

#197 1.2.0
  .eslintrc.js
  README.md
  app/backgroundScript/index.js
  app/contentScript/index.js
  app/lib/MessageDuplex/handlers/child.js
  app/lib/MessageDuplex/handlers/host.js
  app/lib/MessageDuplex/index.js
  app/lib/communication/EventDispatcher.js
  app/lib/communication/PortChild.js
  app/lib/communication/PortHost.js
  manifest.json
  package.json
  yarn.lock
Labels: enhancement, review

#198 add sign string
  app/backgroundScript/index.js
  app/lib/constants.js
  app/pageHook/index.js
  app/popup/src/components/Queue/Renderers/SignedString.js
  app/popup/src/components/Queue/index.js
  manifest.json
  package.json
  yarn.lock
Labels: review
