Repository TronWatch/TronLink, pull requests merged in 2018-08, with the labels that each got.

#100 Fixes #99 - Correct unit conversion on send screen
  app/backgroundScript/index.js
  app/lib/communication/popup/PopupClient.js
  app/lib/communication/popup/PopupHost.js
  app/pageHook/api/v1/index.js
  app/popup/src/components/Header/Send/index.js
  app/popup/src/index.js
  app/popup/src/pages/Account/index.js
  app/popup/src/pages/Queue/CreateSmartcontract/index.js
  app/popup/src/pages/Queue/SendTRX/index.js
  app/popup/src/pages/Send/SendView/index.js
  app/popup/src/reducers/confirmations.js
  app/popup/src/reducers/index.js
  app/popup/src/reducers/wallet.js
  package-lock.json
  package.json
Labels: bug, enhancement, review

#102 Fixes #101 - Add loading overlay, error message in send transaction view
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/popup/src/components/Icons.js
  app/popup/src/pages/Account/AccountView/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Account/index.js
  app/popup/src/pages/Send/SendView/Send.css
  app/popup/src/pages/Send/SendView/index.js
Labels: User Interface, enhancement, review

#103 Fixed: Welcome Page Logo
  app/popup/src/pages/Welcome/Welcome.css
  app/popup/src/pages/Welcome/index.js
Labels: review

#105 Websocket alerts
  app/backgroundScript/index.js
  app/backgroundScript/websocket.js
Labels: review

#108 Correct husky version
  package-lock.json
Labels: bug, enhancement, review

#107 Modify smart contract API methods
  app/pageHook/api/v1/index.js
Labels: Smart Contracts, Website API, enhancement, review

#115 Change deploy contract to http endpoint
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/constants.js
  app/pageHook/api/v1/index.js
  yarn.lock
Labels: Smart Contracts, enhancement, ops, review

#118 Fixes #117 - Handle multiple ports with same source better
  app/lib/communication/PortHost.js
Labels: bug, review

#119 Added "press enter" on welcome page for Wallet creation
  app/popup/src/pages/Welcome/index.js
Labels: review

#121 Build instructions in readme
  README.md
Labels: enhancement, review

#123 Add localisation to popup
  app/popup/src/components/App/index.js
  app/popup/src/index.js
  app/popup/src/pages/Account/AccountView/Tokens/Tokens.css
  app/popup/src/pages/Account/AccountView/Tokens/index.js
  app/popup/src/pages/Account/AccountView/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Account/AccountView/Transactions/Transaction/index.js
  app/popup/src/pages/Account/AccountView/Transactions/index.js
  app/popup/src/pages/Account/AccountView/index.js
  app/popup/src/pages/Give/GiveView/Give.css
  app/popup/src/pages/Give/GiveView/index.js
  app/popup/src/pages/Import/index.js
  app/popup/src/pages/Queue/Renderers/CreateSmartContract.js
  app/popup/src/pages/Queue/Renderers/SendTron.js
  app/popup/src/pages/Queue/index.js
  app/popup/src/pages/Send/AddressView/index.js
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Settings/SettingsView/Settings.css
  app/popup/src/pages/Settings/SettingsView/index.js
  app/popup/src/reducers/wallet.js
  app/popup/src/translations/en.json
  app/popup/src/translations/fr.json
  package-lock.json
  package.json
  yarn.lock
Labels: User Interface, enhancement, review

#122 triggersmartcontract
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/communication/popup/PopupClient.js
  app/lib/constants.js
  app/pageHook/api/v1/index.js
  app/popup/src/pages/Queue/Renderers/TriggerSmartContract.js
  app/popup/src/pages/Queue/index.js
  app/popup/src/reducers/confirmations.js
  yarn.lock
Labels: review

#124 Remove codacy integration
  README.md
Labels: bug, review

#125 Add localisation to triggerSmartContract confirmation
  app/popup/src/pages/Queue/Renderers/TriggerSmartContract.js
  app/popup/src/reducers/confirmations.js
  app/popup/src/reducers/wallet.js
  app/popup/src/translations/en.json
  app/popup/src/translations/fr.json
Labels: enhancement, review

#129 Add PT-BR support language and missing translations
  app/popup/src/components/Header/AccountView/index.js
  app/popup/src/index.js
  app/popup/src/pages/Account/index.js
  app/popup/src/pages/Give/index.js
  app/popup/src/pages/Settings/index.js
  app/popup/src/translations/en.json
  app/popup/src/translations/fr.json
  app/popup/src/translations/pt.json
Labels: enhancement

#131 Closes #126 - Add node selection
  app/backgroundScript/index.js
  app/backgroundScript/nodeSelector.js
  app/backgroundScript/wallet.js
  app/lib/communication/popup/PopupHost.js
  app/lib/constants.js
  app/lib/utils.js
  app/pageHook/api/v1/index.js
  app/popup/src/index.js
  app/popup/src/pages/Settings/SettingsView/Settings.css
  app/popup/src/pages/Settings/SettingsView/index.js
  app/popup/src/reducers/wallet.js
  package.json
  yarn.lock
Labels: User Interface, enhancement, review

#132 Closes #130 - bip39 + bip44 account generation
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/AccountHandler.js
  app/lib/communication/popup/PopupHost.js
  app/lib/constants.js
  app/lib/utils.js
  app/popup/src/components/App/App.css
  app/popup/src/components/App/index.js
  app/popup/src/components/Header/AccountView/AccountView.css
  app/popup/src/components/Header/Header.css
  app/popup/src/components/Header/index.js
  app/popup/src/components/Queue/Queue.css
  app/popup/src/components/Queue/Renderers/CreateSmartContract.js
  app/popup/src/components/Queue/Renderers/SendTron.js
  app/popup/src/components/Queue/Renderers/TriggerSmartContract.js
  app/popup/src/components/Queue/index.js
  app/popup/src/components/Welcome/Welcome.css
  app/popup/src/components/Welcome/index.js
  app/popup/src/pages/Account/AccountView/AccountView.css
  app/popup/src/pages/Account/AccountView/index.js
  app/popup/src/pages/Accounts/Accounts.css
  app/popup/src/pages/Accounts/index.js
  app/popup/src/pages/Give/index.js
  app/popup/src/pages/Redeem/Redeem.css
  app/popup/src/pages/Redeem/index.js
  app/popup/src/pages/Send/AddressView/index.js
  app/popup/src/pages/Send/Send.css
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Settings/Settings.css
  app/popup/src/pages/Settings/SettingsView/index.js
  app/popup/src/pages/Settings/index.js
  app/popup/src/pages/Tokens/Tokens.css
  app/popup/src/pages/Tokens/index.js
  app/popup/src/pages/Transactions/AccountHeader/AccountHeader.css
  app/popup/src/pages/Transactions/AccountHeader/index.js
  app/popup/src/pages/Transactions/TransactionList/Transaction/Transaction.css
  app/popup/src/pages/Transactions/TransactionList/Transaction/index.js
  app/popup/src/pages/Transactions/TransactionList/Transactions.css
  app/popup/src/pages/Transactions/TransactionList/index.js
  app/popup/src/pages/Transactions/Transactions.css
  app/popup/src/pages/Transactions/index.js
  app/popup/src/reducers/wallet.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, review

#133 Finish account page
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/communication/popup/PopupHost.js
  app/popup/src/components/App/App.css
  app/popup/src/components/Header/index.js
  app/popup/src/pages/Accounts/Accounts.css
  app/popup/src/pages/Accounts/index.js
  app/popup/src/pages/Transactions/AccountHeader/index.js
  app/popup/src/reducers/wallet.js
  app/popup/src/translations/en.json
Labels: User Interface, enhancement, review

#141 Export account page and other minor changes
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/communication/popup/PopupHost.js
  app/lib/utils.js
  app/popup/src/components/CreateSuccess/CreateSuccess.css
  app/popup/src/components/CreateSuccess/checkmark.json
  app/popup/src/components/CreateSuccess/index.js
  app/popup/src/components/ExportAccount/ExportAccount.css
  app/popup/src/components/ExportAccount/index.js
  app/popup/src/components/Icons.js
  app/popup/src/components/Welcome/index.js
  app/popup/src/pages/Accounts/index.js
  app/popup/src/pages/Redeem/index.js
  app/popup/src/pages/Send/AddressView/AddressView.css
  app/popup/src/pages/Send/AddressView/index.js
  app/popup/src/pages/Send/Send.css
  app/popup/src/pages/Send/index.js
  app/popup/src/pages/Transactions/AccountHeader/AccountHeader.css
  app/popup/src/pages/Transactions/Transaction/Transaction.css
  app/popup/src/pages/Transactions/Transaction/index.js
  app/popup/src/pages/Transactions/TransactionList/Transactions.css
  app/popup/src/pages/Transactions/TransactionList/index.js
  app/popup/src/pages/Transactions/Transactions.css
  app/popup/src/pages/Transactions/index.js
  app/popup/src/translations/en.json
  package.json
  yarn.lock
Labels: User Interface, enhancement, review

#143 Contract call simulation
  app/backgroundScript/index.js
  app/pageHook/api/v1/index.js
  yarn.lock
Labels: Smart Contracts, enhancement, review

#145 Add all import pages and the functionality behind them
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/communication/popup/PopupHost.js
  app/lib/utils.js
  app/lib/wordList.json
  app/popup/src/components/App/index.js
  app/popup/src/components/ExportAccount/ExportAccount.css
  app/popup/src/components/Welcome/index.js
  app/popup/src/pages/Accounts/index.js
  app/popup/src/pages/Import/Import.css
  app/popup/src/pages/Import/MnemonicPhrase/index.js
  app/popup/src/pages/Import/PrivateKey/PrivateKey.css
  app/popup/src/pages/Import/PrivateKey/index.js
  app/popup/src/pages/Import/TronScan/TronScan.css
  app/popup/src/pages/Import/TronScan/index.js
  app/popup/src/pages/Import/TronWatch/TronWatch.css
  app/popup/src/pages/Import/TronWatch/index.js
  app/popup/src/pages/Import/index.js
  app/popup/src/pages/Send/AddressView/index.js
  app/popup/src/translations/en.json
  package-lock.json
  package.json
  yarn.lock
Labels: User Interface, enhancement, review

#147 send asset
  app/backgroundScript/index.js
  app/backgroundScript/wallet.js
  app/lib/constants.js
  app/popup/src/components/Queue/Renderers/SendAsset.js
  app/popup/src/components/Queue/index.js
  yarn.lock
Labels: review

#146 Only mark created accounts as internal
  app/backgroundScript/wallet.js
  app/lib/AccountHandler.js
Labels: bug, review

#148 UI: Token page
  app/popup/src/pages/Tokens/Tokens.css
  app/popup/src/pages/Tokens/index.js
  app/popup/src/pages/Transactions/AccountHeader/index.js
  app/popup/src/translations/en.json
Labels: User Interface, enhancement, review

#149 Add custom node selection
  app/backgroundScript/index.js
  app/backgroundScript/nodeSelector.js
  app/backgroundScript/websocket.js
  app/lib/communication/popup/PopupHost.js
  app/lib/utils.js
  app/popup/src/index.js
  app/popup/src/pages/Settings/Settings.css
  app/popup/src/pages/Settings/index.js
  app/popup/src/pages/Transactions/AccountHeader/index.js
  app/popup/src/reducers/wallet.js
  app/popup/src/translations/en.json
Labels: User Interface, enhancement, review
